---
title: "Project Proposal"
author: "JRLK - Jess Ringness, Rebekah Kim, Laura Cai, Karen Dong"
format: pdf
execute: 
  warning: false
  message: false
editor: visual
---

```{r}
#| label: load-pkg-data
library(tidyverse)
library(tidymodels)
# add other packages as needed

# add code to load data
job_postings <-read.csv("data/job_postings.csv")
benefits <-read.csv("data/benefits.csv")

```

```{r}
job_postings
```
```{r}
unique(benefits$type)
```

```{r}
benefits |>
  select(-inferred) |>
  mutate(count = 1) |>
  pivot_wider(names_from = "type", values_from = "count")
```
```{r}
job_postings |>
  inner_join(benefits, by = 'job_id')
```

```{r}
left(job_postings, benefits, by = 'job_id')
```


```{r}
length(unique(job_postings$job_id))
```

```{r}
length(job_postings$job_id)
```

```{r}
job_postings |>
  filter(job_id == 3690843087)

```


## Introduction

...

## Data description

...

## Initial exploratory data analysis

```{r}
job_postings <- job_postings |> 
  drop_na(applies)
```


```{r}
job_postings |>
  ggplot(aes(x = applies)) +
  geom_histogram()
```

```{r}
summary(job_postings$applies)
```

```{r}

```




```{r}
job_postings |>
  ggplot(aes(x = applies, y = views, color = pay_period)) +
  geom_point() + 
  facet_wrap(~pay_period)
```
```{r}
job_postings |>
  ggplot(aes(x = applies, y = views, color = pay_period)) +
  geom_point() 
```

```{r}
job_postings |>
  ggplot(aes(x = applies, y = views, color = formatted_work_type)) +
  geom_point() + 
  facet_wrap(~formatted_work_type)
```

```{r}
job_postings_exp_na <- job_postings |> 
  drop_na(formatted_experience_level) |>
  filter(formatted_experience_level != "")
```


```{r}
job_postings_exp_na |>
  ggplot(aes(x = applies, y = views, color = formatted_experience_level)) +
  geom_point() + 
  facet_wrap(~formatted_experience_level)
```



```{r}
job_postings |>
  ggplot(aes(x = max_salary, y = views)) +
  geom_point()
```
```{r}
job_postings |>
  ggplot(aes(x = applies, y = views)) +
  geom_point()
```



```{r}
job_postings |>
  ggplot(aes(x = max_salary, y = views, color = sponsored)) +
  geom_point() + 
  facet_wrap(~sponsored)
```
```{r}
unique(job_postings$sponsored)
```



## Analysis approach

...

## Data dictionary

The data dictionary can be found [here](ADD%20LINK!!!) \[Update the link and remove this note!\]
